### ISSUE TITLE
Do not capitalize prompt choices

### ISSUE THREAD

**Issue by JaikrishnaTS** [kausrini/Mini-ScienceDMZ#10]
https://github.com/kausrini/Mini-ScienceDMZ/blob/cc11d81d7ed5c5757b766466d4885e5739e0a949/pi_setup_files/pi_initial_setup.py#L42

Capitalization of one choice (`Y` here) generally means that that would be taken as default if no character is entered.

**Comment by kausrini** [comment]
Fixed
