### ISSUE TITLE
`file` is a reserved keyword in python2

### ISSUE THREAD

**Issue by JaikrishnaTS** [kausrini/Mini-ScienceDMZ#11]
https://github.com/kausrini/Mini-ScienceDMZ/blob/cc11d81d7ed5c5757b766466d4885e5739e0a949/pi_setup_files/pi_initial_setup.py#L128
Wouldn't recommend using it as a variable name.

**Comment by JaikrishnaTS** [comment]
Same at https://github.com/kausrini/Mini-ScienceDMZ/blob/cc11d81d7ed5c5757b766466d4885e5739e0a949/pi_setup_files/pi_initial_setup.py#L256

**Comment by kausrini** [comment]
Fixed
