### ISSUE TITLE
Suggest using a JSON config file for secrets

### ISSUE THREAD

**Issue by JaikrishnaTS** [kausrini/Mini-ScienceDMZ#14]
https://github.com/kausrini/Mini-ScienceDMZ/blob/cc11d81d7ed5c5757b766466d4885e5739e0a949/log_email/sendStatus.py#L21-L24

**Comment by advmarathe** [comment]
Any particular reason why JSON is better than python other than interoperability?

**Comment by JaikrishnaTS** [comment]
The primary reason would be to avoid arbitrary code paths that are unintended. Anyone can place a python module in the location injected to `sys.path` and that would take precedence over packaged modules (say `pi_settings.py`). Even if that possibility is ruled out, any code can be placed in `secrets.py` will be executed as part of this application. 

If a JSON config is used, it is relatively simpler & secure. Also, it provides a clear distinction between user config and application code.
