### ISSUE TITLE
Log Email Functionality needs improvement

### ISSUE THREAD

**Issue by kausrini** [kausrini/Mini-ScienceDMZ#3]
- It would be preferable if the log files that are attached to the mail have an extension like .txt
- The subject of mail currently says "Device status". It would be better if it says "dynv6 domain name:  device status"
- The mail body is empty. Instead the mail body should say generated a diff log for some log file. Unable to generate diff log for some file because there was no change from last log file sent.

**Comment by advmarathe** [comment]
- Adding extension to files broke it for Mac OS. Keeping the files without extension for now.

- Fixed: Device status now has the domain name.

- Mail body indicates what reports are being sent.
